apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
        applicationId: "flinkOnYunikorn-jobmanager"
        queue: "root.sandbox"
    spec:
      schedulerName: yunikorn
      containers:
      - name: jobmanager
        resources:
          requests:
            cpu: "1000m"
            memory: "1024M"
        image: flink:latest
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
